server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devel
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update

GREETING_SERVICE_PASSWORD: abc123456@#
MONITORING_PASSWORD: abc123456@#