server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    driver-class-name: org.postgresql.Driver
    username: ndhai
    password: 121212

ACCOUNT_SERVICE_PASSWORD: abc123456@#
NOTIFICATION_SERVICE_PASSWORD: abc123456@#